name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH and deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run remote commands via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/BizPadi-backend
            git pull origin main
            npm install
            pm2 restart index.js || pm2 start index.js
